Admin Review: open
AG: pending enforcement
AG-EO2: pending enforcement
AG: pending enforcement
Awaiting Hearing Date: open
Awaiting Payment: claimant_won
Closed: claimant_won
Commenced and Continued: open
Dismissed: dismissed
Hearing: open
Imported from SharePoint: closed
Incomplete: dismissed
Manager for Review - D: open
Manager for Review - HC: open
Manager for Review - HD: open
Manager for Review: open
Motion to Reconsider: pending appeal
Open: open
Paid: paid
Pending Closure: open
Pending Referral to AG: pending enforcement
Pending Voucher: open
Refer to Hearing: open
Referred to Hearing: open
Rescheduled: open
Return to FLSD for further investigation: open
Return to WCS: open
Sent for Westlaw: open
Settlement Agreement - AG: claimant_won
Settlement Agreement - IDOL: claimant_won
Stayed: dismissed
Westlaw Completed: open