"2011-06-07": null
7/20/18-Claimant will start receiving $170.39 payments from Bankruptcy Court: closed
Assigned back to Clmt: null
Assign to Clmt/other filing: null
bankrupt: null
Bankrupt: null
BANKRUPT: null
bankruptcy: null
Bankruptcy: null
Became KS Minimum Wage Case DoEUD-4-448: drop
Became KS Minimum Wage Case MW-LyEmp-2-443: drop
Became KS Minimum Wage Case SeDER-2-449: drop
Became KS Minimum Wage Case SeWIC-2-445: drop
Became KS Minimum Wage Case SeWIC-2-451: drop
Became KS Minimum Wage Case WiNEO-2-442: drop
Became KS Minimum Wage Case WyKAC-1-477: drop
Became KS Minimum Wage/Overime Case FiGAC-3-444: drop
Became KS Minimum Wage Overtime Case ShTOP-4-446: drop
Became KS Overtime Case DoLAW-4-453: drop
Became KS Overtime Case DoWAT-4-455: drop
Became KS Overtime Case EIDOR-2-439: drop
Became KS Overtime Case FiGAC-3-452: drop
Became KS Overtime Case JoOLA-1-450: drop
Became KS Overtime Case NeCHA-2-454: drop
Became KS Overtime Case SeWic-2-440: drop
Became KS Overtime Case SeWIC-2-457: drop
Became KS Overtime Case SeWIC-2-458: drop
Became KS Overtime Case SeWIC-2-460: drop
Became KS Overtime Case SeWIC-2-461: drop
Became KS Overtime Case SeWIC-2-462: drop
Became KS Overtime Case SeWIC-2-463: drop
Became KS Overtime Case SeWIC-2-464: drop
Became KS Overtime Case SEWIC-2-465: drop
Became KS Overtime Case SEWIC-2-466: drop
Became KS Overtime Case SEWIC-2-467: drop
Became KS Overtime Case ShAUB-4-459: drop
Became KS Overtime Case ShSIL-4-438: drop
Became KS Overtime Case ShToP-4-441: drop
Both parties deceased: null
BR: null
BR completed/no assets: null
BR filed: null
business closed: null
Called Claimant no wages owed since she received checks: dismissed
Claimant a subcontractor referred him to attorney/Per Tina: dismissed
claimant called/did not want claim processed: withdrawn
claimant did not want to pursue: withdrawn
Claiming UI/Referred to UI: null
clmt deceased: null
Clmt deceased: null
Clmt deceased 10/19: null
Clmt request closure: withdrawn
clmt w/d: withdrawn
Clmt w/d: withdrawn
clmt/wdrawl-paid b4 hearing: withdrawn
CLOSED IN MAY BUT REOPENED IN NOVEMBER 2017: null
"Combined with claim already filed #170080-4": drop
confidential settlement: null
Did not serve BR: null
did not serve/no overtime claim: withdrawn
did not serve per Claimant's request: withdrawn
discussed w/Claimant will revise claim: dismissed
dismissed: dismissed
do not serve per Claimant: withdrawn
Employee waivered penalty: null
ER filed BR/completed: null
ER moved out of state: null
ER out of state/monies from setoff: null
federal claim and outside statute of limitations: null
Federal claim referred to OPM: null
filed in small claims court: null
Got JE only/returned Clmt: null
holding: withdrawn
holding claim per Claimant: withdrawn
Holding per Clmt.: withdrawn
inactive/lost employer: null
incomplete: dismissed
Independent Contractor/returned: dismissed
JE Exp.: null
l: null
lack of jurisdiction: null
"Mandate from Kansas Court of Appeals to Johnson County District Court on March 14, 2019": closed # per response from agency on this case
no address for Resp.: null
no assests: null
no assets: null
No assets: null
no assets/JE exp: null
No assets/wages: null
No Claim: dismissed
no jurisdiction/indepdent contractor: dismissed
no money: null
no money collected: null
no show clmt: null
no svc: null
no svc.: null
No svc.: null
no svc/out of state: null
not an employee: dismissed
not a wage claim: dismissed
Not a wage claim: dismissed
not a wage claim/unemployment LWP: dismissed
Not employee/referred to small claims: dismissed
Notes: drop
not processed/bankrupt: null
not processed/no claim: dismissed
not processed per Claimant: dismissed
not served--bankrupt: null
not served/bankrupt: null
not served/bankruptcy: null
not served due to bankruptcy: null
not served/not a wage claim: dismissed
Not served/order issued on 8/18/17 on this same issue.: drop
not served per Claimant: withdrawn
not served/statute of limitations: null
Obtained JE-assigned back to Clmt.: null
order of dismissal: dismissed
out of business: null
out of state: null
out of state/clmt deceased: null
Owner/operator referred to private atty.: dismissed
Parties met/never heard: null
payments: null
"per Joyce, claimant does not want to pursue": withdrawn
quick claim: null
quick Claim: null
Quick Claim: null
quick claim/no money: null
Refered to the state of Missouri: null
referred to BR court: null
referred to BR Court: null
REFERRED TO EBSA-CLAIM FOR 401K: null
referred to federal: null
referred to Federal: null
Referred to Federal: null
"Referred to Federal  ": null
Referred to Federals: null
referred to feds: null
Referred to Feds: null
referred to feds/EBSA: null
Referred to Florida: null
referred to Kansas Human Rights Commmission: null
referred to Missouri: null
Referred to Missouri: null
Referred to Missouri Department of Labor: null
referred to Missouri DOL: null
referred to MO: null
referred to Nebraska: null
referred to Nebraska DOL: null
Referred to Office of Personnel Mgmt - Federals: null
referred to Oklahoma: null
Referred to Oklahoma: null
referred to OPM/feds: null
referred to state of Missouri: null
"referred to Texas ": null
Referred to Texas: null
Referred to Texas Deparment of Labor: null
Referred to the state of Texas: null
referred to union: null
referred to US Dept of Labor: null
referred to USDOL: null
Referred to USDOL: null
referred to USDOL-overtime claim: null
Respt out of state: null
"resubmitted claim on 1/17/17  #170031-2": drop
returned: null
returned/bankrupt: null
returned/breach contract: null
returned/company defunct: null
returned/corp bankrupt: null
returned/er bankrupt: null
returned  incomplete: dismissed
returned incomplete: dismissed
returned-incomplete: dismissed
returned/incomplete: dismissed
returned/incomplete; no response: dismissed
returned/indep. Contractor: dismissed
returned - independent contractor: dismissed
returned independent contractor: dismissed
returned/independent contractor: dismissed
Returned/independent contractor: dismissed
returned-jurisdiction issue: dismissed
returned/jurisdiction issue: dismissed
returned/lack of jurisdiction/referred to Ohio Dept. of Commerce: dismissed
returned/lack of jurisdiction/subcontractor: dismissed
returned/Missouri: null
Returned/more information: dismissed
returned/needs revision: dismissed
returned-no claim: dismissed
returned/no claim: dismissed
returned/no jurisdiction: dismissed
returned/not a claim: dismissed
returned/not a employee: dismissed
returned-not an employee: dismissed
returned/not an employee: dismissed
returned not a wage claim: dismissed
returned/not a wage claim: dismissed
Returned/not a wage claim: dismissed
returned-not employment: dismissed
returned/not wage issue: dismissed
returned/out of state employee: dismissed
returned/referred to Federal: null
returned/referred to feds: null
returned - referred to Missouri: null
returned/referred to Missouri: null
Returned referred to MO: null
returned/referred to NE: null
returned/referred to Nebraska: null
Returned/referred to UI: null
returned/respondent BR/Respt deceased: null
returned/revise claim: dismissed
returned/statute of limitations: null
returned-statute of limitations (2017 claim): null
returned/subcontractor: dismissed
Returned/subcontractor: dismissed
returned to be revised: dismissed
returned/to be revised: dismissed
returned to Claimant: dismissed
Returned to Claimant/indep. Contractor: dismissed
returned to Claimant/more info.: dismissed
Returned to Claimant/statute of limitations expired: null
returned to employee: dismissed
returned to modify: dismissed
returned to revise: dismissed
returned/to revise: dismissed
returned/unable to process: dismissed
returned/worked in FL and a bankruptcy: null
same claim previously filed-see 200031-2: drop
spoke w/clmt-no wage claim: dismissed
talked to Clmt-not a valid wage claim: dismissed
temporary hold: null
to Tina for translation: null
unable to locate: null
unable to locate assets: null
uncollectable/resp in prison: null
waiting on info from Claimant: null
w/drawal: withdrawn
w/drawal-clt: withdrawn
withdrawal: withdrawn
wtihdrawal: withdrawn